"""empty message

<<<<<<< HEAD:migrations/versions/ea032af1fba6_.py
Revision ID: ea032af1fba6
Revises: 
Create Date: 2021-03-10 15:20:00.936883
=======
Revision ID: 89adb9e481db
Revises: 
Create Date: 2021-03-10 15:38:22.341808
>>>>>>> e77400cc6b749a1f8215359332937cacf8883c00:migrations/versions/89adb9e481db_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/ea032af1fba6_.py
revision = 'ea032af1fba6'
=======
revision = '89adb9e481db'
>>>>>>> e77400cc6b749a1f8215359332937cacf8883c00:migrations/versions/89adb9e481db_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_me', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('twitter', sa.String(length=80), nullable=True),
    sa.Column('github', sa.String(length=80), nullable=True),
    sa.Column('linkedin', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
